views/add_user.py
import re
import wtforms.validators
from flask import render_template, request, Blueprint, flash
import boto3
from wtforms import Form, StringField, PasswordField
from werkzeug.utils import secure_filename
from boto3.dynamodb.conditions import Key


class CreateUser(Form):
    email = StringField('Email:', validators=[wtforms.validators.InputRequired()])
    username = StringField('Username:', validators=[wtforms.validators.InputRequired(),
                                                    wtforms.validators.Length(min=3)])
    password = PasswordField('Password:', validators=[wtforms.validators.InputRequired(),
                                                      wtforms.validators.Length(min=5)])


create_user_blueprint = Blueprint('add_user', __name__, template_folder='templates')
s3_client = boto3.client('s3', region_name='us-west-1')
bucket_name = 'program5-pictures-zach'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}


@create_user_blueprint.route('/create_user', methods=['POST', 'GET'])
def create_user():
    form = CreateUser(request.form)
    if request.method == 'POST' and form.validate():
        email = form.email.data.strip()
        username = form.username.data.strip()
        password = form.password.data.strip()
        regex = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
        if not re.fullmatch(regex, email):
            flash('Invalid email format.')
            return render_template('create_user.html', form=form)
        file_to_upload = request.files['filename']
        if file_to_upload and check_file_type(file_to_upload.filename):
            file_name = secure_filename(file_to_upload.filename)
            s3_client.put_object(ACL='public-read', Body=file_to_upload,
                                 Bucket=bucket_name, Key=username + '_' + file_name)
            default = False
        elif not file_to_upload:
            file_name = 'default.png'
            default = True
        else:
            flash('Please upload proper formats. Allowed file type are - png - jpeg - gif - jpg.')
            return render_template("create_user.html", form=form)
        if email == '' or password == '' or username == '':
            return render_template("base.html", place_one='fill out all fields')
        else:
            dynamodb = boto3.resource('dynamodb', region_name='us-west-1')
            table = dynamodb.Table('Program5Users')
            response = table.scan(FilterExpression=Key('username').eq(username))
            if response['Items']:
                flash('Username already exists.')
                return render_template('create_user.html', form=form)
            response = table.scan(FilterExpression=Key('email').eq(email))
            if response['Items']:
                flash('Email already exists.')
                return render_template('create_user.html', form=form)
            elif len(response['Items']) != 1 and default is True:
                table.put_item(
                    Item={'email': email, 'password': password, 'username': username, 'pfp': file_name,
                          'subscribed': 'False'}
                )
            else:
                table.put_item(
                    Item={'email': email, 'password': password, 'username': username,
                          'pfp': username + '_' + file_name, 'subscribed': 'False'}
                )
            return render_template('create_user.html', form=form, created='User has successfully been created!')
    return render_template('create_user.html', form=form)


def file_name_split(file_name):
    name_arr = file_name.split('.')
    return name_arr[0]


def check_file_type(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

views/help.py
from flask import Blueprint, render_template, session, redirect, url_for

help_blueprint = Blueprint('help', __name__, template_folder='templates')


@help_blueprint.route('/help', methods=['GET'])
def ticker_help():
    try:
        _ = session['user']
    except KeyError:
        return redirect(url_for('home_page'))
    return render_template('help.html', user=session['user_name'], user_avatar=session['pfp'])

views/subscribe.py
from flask import Blueprint, render_template, request, session, redirect, url_for
import boto3
from botocore.exceptions import ClientError
from boto3.dynamodb.conditions import Key

sns_client = boto3.client('sns', region_name='us-west-1')
__TableName__ = 'Program5Users'
dynamodb = boto3.resource('dynamodb', region_name='us-west-1')
table = dynamodb.Table(__TableName__)
dynamodb_client = boto3.client('dynamodb', region_name='us-west-1')

subscribe_blueprint = Blueprint('subscribe', __name__, template_folder='templates')


@subscribe_blueprint.route('/subscribe', methods=['GET', 'POST'])
def subscribe():
    try:
        user_email = session['user']
    except KeyError:
        return redirect(url_for('home_page'))
    pfp_link = session['pfp']
    if request.method == 'GET':
        response = table.query(
            KeyConditionExpression=Key('email').eq(user_email)
        )
        profiles = response["Items"]
        user = profiles[0]
        subscribed = False
        if 'subscribed' in user and user['subscribed'] != 'False':
            subscribed = True
        return render_template('subscribe.html', subscribed=subscribed, user_avatar=pfp_link, user=session['user_name'])
    else:
        if 'subscribe' in request.form:
            topic = 'arn:aws:sns:us-west-1:139114520614:crypto_notifications'
            protocol = 'Email'
            endpoint = user_email
            try:
                subscription = sns_client.subscribe(TopicArn=topic, Protocol=protocol, Endpoint=endpoint,
                                                    ReturnSubscriptionArn=True)
                dynamodb_client.update_item(
                    TableName=__TableName__,
                    Key={
                        'email': {'S': user_email}
                    },
                    ExpressionAttributeNames={
                        '#sub': 'subscribed'
                    },
                    UpdateExpression="set #sub = :subs",
                    ExpressionAttributeValues={
                        ':subs': {
                            'S': subscription['SubscriptionArn']
                        }
                    }
                )
                mes = f'Subscribed \"{endpoint}\" to the Email Notification List. ' \
                      'Please confirm the email in your inbox!'
                return f"""<h1> {mes} <h1>
                            <a href="/subscribe">Go back.<a>"""
            except ClientError:
                return f"""<h1>Could not subscribe, please go back to the subscribe page to try again.<h1>
                            <a href="/subscribe">Go back.<a>"""
        else:
            response = table.query(
                KeyConditionExpression=Key('email').eq(user_email)
            )
            profiles = response["Items"]
            user = profiles[0]
            subscription_arn = user['subscribed']
            try:
                sns_client.unsubscribe(SubscriptionArn=subscription_arn)
                dynamodb_client.update_item(
                    TableName=__TableName__,
                    Key={
                        'email': {'S': user_email}
                    },
                    ExpressionAttributeNames={
                        '#sub': 'subscribed'
                    },
                    UpdateExpression="set #sub = :subs",
                    ExpressionAttributeValues={
                        ':subs': {
                            'S': 'False'
                        }
                    }
                )

                return """<h1> Unsubscribed from the Email Notification List! You will no longer receive emails. <h1>
                          <a href="/subscribe">Go back.<a>"""
            except ClientError:
                return """<h1> You cannot unsubscribe at this time. Please confirm the subscription sent to your email 
                               before unsubscribing<h1>
                          <a href="/subscribe">Go back.<a>"""

views/user_api.py
from flask import Blueprint, jsonify, render_template
import boto3
from boto3.dynamodb.conditions import Key

__TableName__ = 'Program5Users'
dynamodb = boto3.resource('dynamodb', region_name='us-west-1')
table = dynamodb.Table(__TableName__)

web_api_blueprint = Blueprint('user_api', __name__, template_folder='templates')


@web_api_blueprint.route('/api/v1/', methods=['GET'])
def api_home():
    return render_template('user_api_home.html')


@web_api_blueprint.route('/api/v1/information/<user>/', methods=['GET'])
def get_user_list(user):
    response = table.scan(FilterExpression=(Key('email').eq(user) | Key('username').eq(user)))
    profiles = response['Items']
    json_attributes = {}
    tickers = {}
    for profile in profiles:
        for attribute in profile:
            if attribute != 'email' and attribute != 'password' and attribute != 'username' and attribute != 'pfp' and \
                    attribute != 'subscribed':
                tickers[attribute] = "https://www.messari.io/asset/" + attribute
            elif attribute != 'password' and attribute != 'subscribed' and attribute != 'pfp':
                json_attributes[attribute] = profile[attribute]
            elif attribute == 'pfp':
                json_attributes[attribute] = 'https://program5-pictures-zach.s3.us-west-1.amazonaws.com/' + \
                                             profile[attribute]
    if len(json_attributes) > 0:
        return jsonify(status_code=200, user_info=json_attributes, tracked_cryptos=tickers)
    else:
        return jsonify(status_code=404, msg="User does not exist.")

templates/add_ticker.html
<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet"  href="{{ url_for('static', filename='css/style.css') }}">
<link rel="icon" type="image/x-icon" href="https://icons.iconarchive.com/icons/pauloruberto/custom-round-yosemite/256/Bitcoin-icon.png">
<div class="topnav">
    <a href="{{url_for('home_page')}}">Home</a>
    <a class="active" href="{{url_for('add_ticker_page.add_ticker')}}">Edit Crypto List</a>
    <a href="{{url_for('help.ticker_help')}}">Help</a>
    <a href="{{url_for('subscribe.subscribe')}}">Subscribe</a>
    <a href="{{url_for('user_api.api_home')}}">Web API</a>
    <a href="{{url_for('logout')}}">Logout</a>
    <img class="rounded-circle article-img" src="{{ user_avatar }}" id="img">
    <b>Username: {{user}}</b>
</div>
<br>
<head>
    <meta charset="UTF-8">
    <title>Crypto List</title>
</head>
<script type="text/javascript">
setTimeout (function(){
    document.getElementById('fetch_asset').disabled = null;
    document.getElementById('spam_text').hidden = true;
}, 6500);
</script>
<body style="color:white">
<form method="POST">
    <div class="tickerdiv">
        {{ form.ticker.label }}
        {{ form.ticker }}
        <input type="submit" value="Fetch" disabled="disabled" name="fetch" id="fetch_asset"> <span id="spam_text">To prevent spam, button is disabled for a few seconds when clicked AND on page load.</span>
        {% if ticker_not_filled_error %}
            <p style="font-size:20px;color:red;"> {{ ticker_not_filled_error }} </p>
        {% endif %}
        {% if invalid_ticker_error %}
            <p style="font-size:20px; color:red;"> {{ invalid_ticker_error }} </p>
        {% endif %}
        {% if fetched_asset %}
            <h3> Data: </h3>
            <textarea name="ticker_and_price" style="color:white;background-color:Transparent;border-color:Transparent;outline:none;font-family:Times New Roman;font-size:20px;resize:none;" readonly>{{ fetched_asset[0] }}: ${{ fetched_asset[1] }} </textarea>
            <br>
            <a href="{{ fetched_asset[3] }}" style="color:green" target="_blank"> Explore {{ fetched_asset[0] }} price on Messari! </a>
            <br>
            {% if fetched_asset[2] == True %}
                <br>
                <input type="submit" value="Add asset to your list" name="add_asset">
            {% elif fetched_asset[2] == 'Max Items' %}
                <br>
                <span> You can only have a maximum of 5 assets. </span>
            {% else %}
                <br>
                <span> This asset already exists in your list. </span>
                <br>
                <br>
                <input type="submit" value="Delete asset from your list" name="delete_asset">
            {% endif %}
        {% endif %}
    </div>
</form>
<br>
<form method="POST">
    <hr>
    {% if item %}
        <h3> Your Tracked Cryptos: </h3>
        {% for ticker in item %}
            {{ ticker }}
            <input type="submit" value="Remove {{ ticker }}" name="remove">
            <br>
            <br>
        {% endfor %}
        <input type="submit" value="Remove All" name="remove_all">
    {% else %}
        <h2> Some cryptos you can try to fetch: ETH (aka Ethereum), BTC (aka Bitcoin), LTC (aka Litecoin). </h2>
        <h2> Still confused? Check out the "Help" tab! </h2>
    {% endif %}
</form>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html>
    <link rel="stylesheet"  href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="icon" type="image/x-icon" href="https://icons.iconarchive.com/icons/pauloruberto/custom-round-yosemite/256/Bitcoin-icon.png">
    <title>Crypto Tracker</title>

    <div class="topnav">
        <a class="active" href="{{url_for('home_page')}}">Home</a>
        <a href="{{url_for('add_user.create_user')}}">Create Account</a>
        <a href="{{url_for('user_api.api_home')}}">Web API</a>
    </div>
    <body>
    <h4 style="color:white">Welcome to Crypto Tracker! Here, you will be able to view various Cryptocurrencies and also be able to track them. Create an account or login below to get started! </h4>
       <h1>Login</h1>
     <form method="POST">
        <div class="login">
             <b> {{ form.email_username.label }} </b>
             <br><br>
             {{ form.email_username(size=40) }}
             <br><br>
             <b> {{ form.password.label }} </b>
             <br><br>
             {{ form.password(size=40) }}
            <br><br>
            <input type="submit" value="Login">
         </div>
    </form>
    <h3 style="color:red">{{login_fail}}</h3>
<br><br>

</body>
</html>

templates/create_user.html
<!DOCTYPE html>
<html>
<script>
if ( window.history.replaceState ) {
  window.history.replaceState( null, null, window.location.href );
}
</script>
    <link rel="stylesheet"  href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="icon" type="image/x-icon" href="https://icons.iconarchive.com/icons/pauloruberto/custom-round-yosemite/256/Bitcoin-icon.png">
    <div class="topnav">
        <a href="{{url_for('home_page')}}">Home</a>
        <a class="active" href="{{url_for('add_user.create_user')}}">Create Account</a>
        <a href="{{url_for('user_api.api_home')}}">Web API</a>
    </div>
    <title>Create Account</title>

    <body style="color:white">
    <h1>Create Account</h1>

     <form method="POST" enctype="multipart/form-data">
         <div class="create_user">
             <b> {{ form.email.label }} </b>
             <br><br>
             {{ form.email(size=40) }}
             <br><br>
             <b> {{ form.username.label }} </b>
             <br><br>
             {{ form.username(size=40) }}
             <br><br>
             <b> {{ form.password.label }} </b>
             <br><br>
             {{ form.password(size=40) }}
             <br><br>
             <b> Profile Picture (Optional): </b><br><br> <input type="file" name="filename">
             <br><br>
             <input type="submit" name="submit_form" value="Create Account">
         </div>
         {% with messages = get_flashed_messages() %}
          {% if messages %}
            {% for message in messages %}
                <h3 style="color:red"> {{ message }} </h3>
            {% endfor %}
          {% endif %}
        {% endwith %}
        {% if created %}
            <h3 style="color:green"> {{ created }} </h3>
        {% endif %}
    </form>
</body>
</html>

templates/help.html
<!DOCTYPE html>
<html lang="en">
<head>
<link rel="stylesheet"  href="{{ url_for('static', filename='css/style.css') }}">
<link rel="icon" type="image/x-icon" href="https://icons.iconarchive.com/icons/pauloruberto/custom-round-yosemite/256/Bitcoin-icon.png">
<div class="topnav">
    <a href="{{url_for('home_page')}}">Home</a>
    <a href="{{url_for('add_ticker_page.add_ticker')}}">Edit Crypto List</a>
    <a class="active" href="{{url_for('help.ticker_help')}}">Help</a>
    <a href="{{url_for('subscribe.subscribe')}}">Subscribe</a>
    <a href="{{url_for('user_api.api_home')}}">Web API</a>
    <a href="{{url_for('logout')}}">Logout</a>
    <img class="rounded-circle article-img" src="{{ user_avatar }}" id="img">
    <b>Username: {{user}}</b>
</div>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="color:white">
    <h1> Confused on how to get the Crypto you want to track? Follow these steps below.</h1>
    <h2> Step 1: </h2> <p> Visit <a style="color:green" href="https://messari.io/" target="_blank">Messari</a></p>
    <h2> Step 2: </h2> <p> Locate this section on the bottom left of the screen: </p>
    <p> <img alt="Messari Website" src="https://i.ibb.co/2cVTXj6/Screen-Shot-2022-03-05-at-13-17-47.jpeg" height="500px" width="500px"> </p>
    <h2> Step 3: </h2> <p> Click any one of these Cryptos or click on the next page to see more and find one you want to track. </p>
    <h2> Step 4: </h2> <p> After finding an asset you want to track, click on it. </p>
    <h2> Step 5: </h2> <p> Check the URL. You should see something like "https://messari.io/asset/xrp". In this case, the ticker name is "xrp" (the last part of the URL). </p>
    <h2> Step 6: </h2> <p> Copy the ticker name and head back to "Edit Crypto List" and paste it into the field. </p>
    <h2> Step 7: </h2> <p> Click "Fetch"! </p>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home page</title>
</head>
<body>
<form method="POST">
    <div class="ticker">
        {{ form.ticker.label }}
        {{ form.ticker }}
        <input type="submit" value="Add" name="add">
        {% if ticker_not_filled %}
            <p style="font-size:20px; color:orange;"> {{ ticker_not_filled }} </p>
        {% endif %}
    </div>
</form>
</body>
</html>

templates/logged_in.html
<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet"  href="{{ url_for('static', filename='css/style.css') }}">
<link rel="icon" type="image/x-icon" href="https://icons.iconarchive.com/icons/pauloruberto/custom-round-yosemite/256/Bitcoin-icon.png">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<script type="text/javascript">
setTimeout (function(){
    document.getElementById('refresh_btn').disabled = null;
    document.getElementById('spam_text').hidden = true;
}, 30000);
</script>
<body style="color:white">
     <div class="topnav">
         <a class="active" href="{{url_for('logged_in_page')}}">Home</a>
         <a href="{{url_for('add_ticker_page.add_ticker')}}">Edit Crypto List</a>
         <a href="{{url_for('help.ticker_help')}}">Help</a>
         <a href="{{url_for('subscribe.subscribe')}}">Subscribe</a>
         <a href="{{url_for('user_api.api_home')}}">Web API</a>
         <a href="{{url_for('logout')}}">Logout</a>
         <img class="rounded-circle article-img" src="{{ user_avatar }}" id="img">
         <b>Username: {{user}}</b>
     </div>
{% if item %}
        <h3> <center> Your Tracked Cryptos: </center> </h3>
        {% for asset in item %}
            <center> {{ asset[0] }}: ${{ asset[1] }} </center>
            <hr>
        {% endfor %}
        <form method="POST">
            <center> <input disabled="disabled" type="submit" value="Refresh Prices" name="refresh" id="refresh_btn"> </center>
            <br>
            <center> <span id="spam_text">To prevent spam, button is disabled for 30 seconds when clicked AND on page load.</span> </center>
        </form>
{% else %}
     <h2> You are not tracking any Cryptos currently. Check out "Edit Crypto List" to add a crypto to track! </h2>
{% endif %}
</body>
</html>

templates/subscribe.html
<!DOCTYPE html>
<title>Subscribe</title>
<html>
<body>
<link rel="stylesheet"  href="{{ url_for('static', filename='css/style.css') }}">
<link rel="icon" type="image/x-icon" href="https://icons.iconarchive.com/icons/pauloruberto/custom-round-yosemite/256/Bitcoin-icon.png">
<div class="topnav">
    <a href="{{url_for('home_page')}}">Home</a>
    <a href="{{url_for('add_ticker_page.add_ticker')}}">Edit Crypto List</a>
    <a href="{{url_for('help.ticker_help')}}">Help</a>
    <a class="active" href="{{url_for('subscribe.subscribe')}}">Subscribe</a>
    <a href="{{url_for('user_api.api_home')}}">Web API</a>
    <a href="{{url_for('logout')}}">Logout</a>
    <img class="rounded-circle article-img" src="{{ user_avatar }}" id="img">
    <b>Username: {{user}}</b>
</div>
<!-- don't show button if they are subscribed -->
{% if not subscribed %}
<h2 style="color: white">This is an Email Notification List for BTC, ETH, and LTC. Updates are provided every 15 minutes, and you will be notified of price changes. Click subscribe to join the list!</h2>
<form method="POST">
    <button name="subscribe">Subscribe</button>
</form>
{% else %}
<form method="POST">
    <h1 style="color: white">You should now receive price updates every 15 minutes! Click unsubscribe to leave the Email Notification List.</h1>
    <button name="unsubscribe">Unsubscribe</button>
</form>
{% endif %}

<!-- show unsubscribe if they are subbed -->
</body>
</html>

templates/user_api_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Web API</title>
</head>
<link rel="stylesheet"  href="{{ url_for('static', filename='css/style.css') }}">
<link rel="icon" type="image/x-icon" href="https://icons.iconarchive.com/icons/pauloruberto/custom-round-yosemite/256/Bitcoin-icon.png">
<div class="topnav">
    <a href="{{url_for('home_page')}}">Home</a>
    <a class="active" href="{{url_for('user_api.api_home')}}">Web API</a>
</div>
<body style="color:white">
    <h4>
    Welcome to our Web API! This is a simple API which supports GET requests. For now there is only one endpoint supported.
    With this endpoint, you can get information about a user by requesting the email OR the username of an account.
    <br><br>The format of the GET requests looks like this:
    <br><br>GET http://program5-env.eba-6cvwcsgc.us-west-1.elasticbeanstalk.com/api/v1/information/{EMAIL | USERNAME}
    <br><br>For example: GET http://program5-env.eba-6cvwcsgc.us-west-1.elasticbeanstalk.com/api/v1/information/dimpsey<br><br>
    The information you get back for a successful 200 response will look something like this:
    <pre>
        <code style="font-size:15px">
{
    "status_code": 200,
    "tracked_cryptos": {
        "BTC": "https://www.messari.io/asset/BTC",
        "ETH": "https://www.messari.io/asset/ETH",
        // ... more cryptos
    },
    "user_info": {
        "email": "email@gmail.com",
        "pfp": "https://bucket.s3.us-west-1.amazonaws.com/pfp.jpeg",
        "username": "username"
    }
}
        </code>
    </pre>
        Note that there is also a 404 response for an account that does not exist.
        <br><br>The next step is to add endpoints for programmatically adding Cryptos to your user list without
        interacting with the UI (a POST request)!
    </h4>
</body>
</html>